/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chessoid_liaison_jni_Liaison */

#ifndef _Included_com_chessoid_liaison_jni_Liaison
#define _Included_com_chessoid_liaison_jni_Liaison
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chessoid_liaison_jni_Liaison
 * Method:    testliaison
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chessoid_liaison_jni_Liaison_testliaison
  (JNIEnv *, jclass);

/*
 * Class:     com_chessoid_liaison_jni_Liaison
 * Method:    init_engine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_chessoid_liaison_jni_Liaison_init_1engine
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
